# -------- Stage 1: Build with Gradle on GraalVM JDK 25 ----------
FROM ghcr.io/graalvm/native-image-community:25-ol9 as build-stage

# Install findutils to fix "xargs is not available" error when running ./gradlew commands
RUN microdnf install -y --setopt=install_weak_deps=0 --nodocs findutils \
    && microdnf clean all

# Install nodejs
RUN microdnf module enable nodejs:22
RUN microdnf install -y nodejs npm

ARG WORKDIR=/app
WORKDIR /app

# Copy Gradle configuration
COPY gradlew ./gradlew
COPY gradle ./gradle

# Copy project sources
COPY app ./app
COPY server ./server
COPY web ./web
COPY settings.gradle ./settings.gradle

# Build ui
RUN npm install --prefix ./web
RUN npm run build --prefix ./web

RUN --mount=type=cache,target=${WORKDIR}/.gradle \
    --mount=type=cache,target=/root/.gradle \
    ./gradlew help

RUN --mount=type=cache,target=${WORKDIR}/.gradle \
    --mount=type=cache,target=/root/.gradle \
    ./gradlew -x test nativeCompile -Dorg.gradle.configuration-cache=false

# -------- Stage 2: Running application ----------
FROM alpine:3 AS release-stage

# Install the `gcompat` package in your Alpine Dockerfile to provide a compatibility layer for `glibc` binaries.
RUN apk add --no-cache gcompat
# Copy artifact
COPY --from=build-stage /app/app/build/native/nativeCompile/app /app/app
# Set the timezone to Berlin
ENV TZ=Europe/Berlin
# Run the application
ENTRYPOINT ["/app/app"]
