# -------- Stage 1: Build with Gradle on GraalVM JDK 25 ----------
FROM ghcr.io/graalvm/native-image-community:25-ol9 as build-stage

# Install findutils to fix "xargs is not available" error when running ./gradlew commands
RUN microdnf install -y --setopt=install_weak_deps=0 --nodocs findutils \
    && microdnf clean all

# Install nodejs
RUN microdnf module enable nodejs:22
RUN microdnf install -y nodejs npm

ARG WORKDIR=/app
WORKDIR /app

# Copy Gradle configuration
COPY gradlew ./gradlew
COPY gradle ./gradle

# Copy project sources
COPY app ./app
COPY server ./server
COPY web ./web
COPY settings.gradle ./settings.gradle

# Build ui
RUN npm install --prefix ./web
RUN npm run build --prefix ./web

RUN --mount=type=cache,target=${WORKDIR}/.gradle \
    --mount=type=cache,target=/root/.gradle \
    ./gradlew help

RUN --mount=type=cache,target=${WORKDIR}/.gradle \
    --mount=type=cache,target=/root/.gradle \
    ./gradlew -x test nativeCompile -Dorg.gradle.configuration-cache=false

# -------- Stage 2: Running application ----------
FROM alpine:3 AS release-stage

# Install the `gcompat` package in your Alpine Dockerfile to provide a compatibility layer for `glibc` binaries.
RUN apk add --no-cache gcompat
# Copy artifact
COPY --from=build-stage /app/app/build/native/nativeCompile/app /app/app
# Set the timezone to Berlin
ENV TZ=Europe/Berlin
# Run the application
ENTRYPOINT ["/app/app"]

# # ==========================
# # Build Stage
# # ==========================
# FROM gradle:jdk25-alpine AS build-stage

# WORKDIR /app

# # Install build dependencies
# RUN apk add --no-cache nodejs npm unzip

# # Copy Gradle configuration
# COPY gradlew ./gradlew
# COPY gradle ./gradle

# # Copy project sources
# COPY app ./app
# COPY server ./server
# COPY web ./web
# COPY settings.gradle ./settings.gradle

# # Build ui
# RUN npm install --prefix ./web
# RUN npm run build --prefix ./web

# # Build the project (skip tests)
# RUN ./gradlew build copyDeps -x test

# RUN jdeps --ignore-missing-deps -q \
# --recursive \
# --multi-release 25 \
# --print-module-deps \
# --class-path 'app/build/dependencies/*' \
# app/build/libs/app.jar > deps.info

# RUN jlink \
# --add-modules $(cat deps.info),java.management \
# --strip-debug \
# --compress zip-6 \
# --no-header-files \
# --no-man-pages \
# --output /productionjre

# # Unpack build distribution
# RUN unzip ./app/build/distributions/app.zip -d /distro

# # ==========================
# # Runtime Stage
# # ==========================docker 
# FROM alpine:latest AS release-stage

# # Copy the custom runtime and built app
# ENV JAVA_HOME=/opt/java/openjdk
# ENV PATH="$JAVA_HOME/bin:$JAVA_HOME/lib:$PATH"
# COPY --from=build-stage /productionjre $JAVA_HOME

# COPY --from=build-stage /distro/app/ $JAVA_HOME

# WORKDIR $JAVA_HOME

# # Optionally expose the server port
# # EXPOSE 8081

# ENTRYPOINT ["bin/app"]
